version: "3.9"

services:
  # SERVICIO WEB (REACT + NGINX)
  tarkov-web:
    image: ublcdtarkov
    container_name: ctlcdtarkov
    build:
      context: ../../              # <--- ¡CRUCIAL! Miramos desde la raíz 'Linas'
      dockerfile: deploy/04_react/Dockerfile
    env_file: .env
    ports:
      - "1987:80"             # <--- Tu puerto para Tarkov
      - "${PORT_NODE}:3000"   # Puerto desarrollo
      - "${PORT_SSH}:22"
    volumes:
      - ./logs:/root/logs
    networks:
      - red_tarkov
    restart: always

  # SERVICIO BASE DE DATOS
  mariadb:
    image: mariadb:10.6
    container_name: ctlcdmariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    networks:
      - red_tarkov
    volumes:
      - datos_db:/var/lib/mysql
    restart: always

  # SERVICIO GESTIÓN (phpMyAdmin)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ctlcdphpmyadmin
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
    ports:
      - "1990:80"             # <--- Tu puerto para la Base de Datos
    networks:
      - red_tarkov
    depends_on:
      - mariadb
    restart: always

networks:
  red_tarkov:
    driver: bridge

volumes:
  datos_db: