version: '3.9'

services:
  portfolio:
    image: ublcdnginx:latest
    container_name: ctlcdportfolio
    build:
      context: ../../
      dockerfile: deploy/05_portfolio/Dockerfile  # <--- CORREGIDO
    ports:
      - "1974:80"       # Puerto Portafolio
      - "2222:22"
    networks:
      - red_portfolio
    restart: always

networks:
  red_portfolio:
    driver: bridge