version: '3.9'

services:
  portfolio:
    # --- CAMBIO IMPORTANTE ---
    # Le damos un nombre ÃšNICO a esta imagen para que no se mezcle
    image: ublcdportfolio:latest 
    container_name: ctlcdportfolio
    build:
      context: ../../
      dockerfile: deploy/05_portfolio/dockerfile
    ports:
      - "1974:80"
      - "2222:22"
    networks:
      - red_portfolio
    restart: always

networks:
  red_portfolio:
    driver: bridge