services:
  autocaravaneando:
    image: ublcdreact
    container_name: ctlcdreact
    build: .
    env_file: .env
    ports:
      - "${PORT_WWW}:80"
      - "${PORT_NODE}:3000"
      - "${PORT_SSH}:22"
    volumes:
      - ./logs:/root/logs
    restart: always