version: "3.9"

services:
  # 1. TU APP PRINCIPAL (La arquitectura de 4 capas que ya tienes)
  autocaravaneando:
    image: ublcdreact
    container_name: ctlcdreact
    build: .
    env_file: .env
    ports:
      - "${PORT_WWW}:80"      # Tu web de producción (Nginx)
      - "${PORT_NODE}:3000"   # Tu web de desarrollo (Vite)
      - "${PORT_SSH}:22"      # SSH y Auditoría
    volumes:
      - ./logs:/root/logs
    networks:
      - red_tarkov
    restart: always

  # 2. NUEVO SERVICIO: BASE DE DATOS (MariaDB)
  mariadb:
    image: mariadb:10.6
    container_name: ctlcdmariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    networks:
      - red_tarkov
    volumes:
      - datos_db:/var/lib/mysql
    restart: always

  # 3. NUEVO SERVICIO: GESTIÓN WEB (phpMyAdmin)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ctlcdphpmyadmin
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
    ports:
      - "${PORT_PMA}:80"  # Puerto nuevo para administrar la DB
    networks:
      - red_tarkov
    depends_on:
      - mariadb
    restart: always

# Redes y Volúmenes
networks:
  red_tarkov:
    driver: bridge

volumes:
  datos_db: