apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tarkov-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: tarkov.local  # <--- Este serÃ¡ el nombre para entrar
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tarkov-service
            port:
              number: 80